# --- Original Tasks (for macOS/Linux) ---
[tasks.submodule-init]
run = "git submodule update --init --recursive"

[tasks.make-build-folder]
run = "mkdir -p ReacomaExtension/build"
hide = true

[tasks.configure-deployment]
run = "cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DDEPLOYMENT_BUILD=ON"
dir = "ReacomaExtension/build"
depends = ["make-build-folder"]

[tasks.build]
run = "ninja"
dir = "ReacomaExtension/build"

[tasks.deploy]
description = "Configures and builds for macOS/Linux."
run = [
  "mise run make-build-folder",
  "mise run configure-deployment",
  "mise run build",
]

[tasks.clean]
run = "rm -rf ReacomaExtension/build"

[tasks.make-build-folder-windows]
run = '''pwsh -Command "New-Item -Path 'ReacomaExtension/build' -ItemType Directory -Force"'''
hide = true

[tasks.configure-deployment-windows]
run = "cmake .. -GNinja -DCMAKE_BUILD_type=Release -DDEPLOYMENT_BUILD=ON"
dir = "ReacomaExtension/build"
depends = ["make-build-folder-windows"]

[tasks.deploy-windows]
description = "Configures and builds for Windows."
run = [
  "mise run make-build-folder-windows",
  "mise run configure-deployment-windows",
  "mise run build",
]

[tasks.clean-windows]
run = '''pwsh -Command "if (Test-Path 'ReacomaExtension/build') { Remove-Item -Path 'ReacomaExtension/build' -Recurse -Force }"'''
